---
title: "Lecture 1"
author: "Bradley Katcher"
date: "2025-08-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preamble:
```{r, echo = T}
# filename.do
# Author: Bradley Katcher
# Date: 
# Purpose: 
# Description:
```

## Packages:
```{r, echo = T}
# to install packages, we use the following function:
#install.packages('dplyr') # you only need to do this once
library(dplyr) # this calls the package, you need to do this every time
library(openxlsx)
```

## storing key variables:
```{r, echo = T}
# store globals here
```


# Begin Analysis

## (1) read in the data sets:
```{r, echo = T}
full_nuclear_data <- read.xlsx('http://www.matthewfuhrmann.com/uploads/2/5/8/2/25820564/nl_dataset_v.1.2.xlsx')
nuclear_country_year <- read.xlsx('http://www.matthewfuhrmann.com/uploads/2/5/8/2/25820564/country-year_dataset.xlsx')
```

## (2) Preview the data:

```{r, echo = T}

# look at the first 5 observations
  head(full_nuclear_data)
  
  # look at data with columns running down the page and data going across:
  glimpse(full_nuclear_data)
  full_nuclear_data |> glimpse()
```

```{r, echo = T}

  # do the same for the smaller data:
  head(nuclear_country_year)
  glimpse(nuclear_country_year)
  
  # get a summary of the data:
  summary(full_nuclear_data)
  summary(full_nuclear_data$military)
  summary(full_nuclear_data |> select(military, size))
```

```{r, echo = T}

  # tabulate the data
  table(full_nuclear_data$enr_type)
  table(full_nuclear_data$enr_type, full_nuclear_data$military)
```

# (4) Begin exercise:
## What share of nuclear and plants in Europe are military as opposed to civilian? What share broken out by technology type?
  
```{r, echo = T}

  # look at the countries:
  table(full_nuclear_data$country_name)
  
  # select just European countries:
  europe_nuclear_data <- full_nuclear_data |> 
    filter(country_name %in% 
             c("Belgium", "Czech Republic", "France", "Germany",
               "Italy", "Netherlands", "Norway", "Romania",
               "Spain", "Sweden", "United Kingdom", "Yugoslavia"))
```

```{r, echo = T}

  # # subset to the variables that we need:
  europe_nuclear_data <- europe_nuclear_data |> 
    select(country_name, enr_type, military)
  
  # get summary stats of the data frame:
  summary(europe_nuclear_data)
```

```{r, echo = T}

  # recode the missing observations:
  military_summary_data <- europe_nuclear_data |> 
    # recode the missing military to be NA
    mutate(military = if_else(military == -99, NA, military))
  
  # look at the result:
  mean(military_summary_data$military, na.rm = T)
```  
  
# Now let's uput it all together: How many military and civilian nuclear plants are there by power type? 
  
```{r, echo = T}

  # compute the number and share of military plants by power type
  europe_power_type <- europe_nuclear_data |>
    # recode the missing to be NA:
    mutate(military = if_else(military == -99, NA, military)) |>
    # remove the missings:
    filter(!is.na(military)) %>%
    #group by power type:
    group_by(enr_type) %>%
    # summarise the share of military
    summarise(military = mean(military), # the share of plants that are military
              n_plants = n()) # the total number of plants by type
  
  # look at the data:
  europe_power_type
```
    
### Clean up the results a bit:
```{r, echo = T}

  # add strings to the power type
  europe_power_type  <- europe_power_type |>
    # create a variable with the name as a string instead of a number
    mutate(power_type = case_when(
      enr_type == 1 ~ "Reprocessing",
      enr_type == 2 ~ "Gaseous diffusion",
      enr_type == 3 ~ "Centrifuge",
      enr_type == 4 ~ "EMIS",
      enr_type == 5 ~ "Chemical & ion exchange",
      enr_type == 6 ~ "Aerodynamic isotope separation",
      enr_type == 7 ~ "Laser",
      enr_type == 8 ~ "Thermal diffusion")) |>
    # remove the number
    select(-enr_type) |>
    # sort by the number of plants (descending)
    arrange(-n_plants) |>
    # make sure that power_type is the first variable:
    select(power_type, everything())
  
  # look at the results:
  europe_power_type
```

